### ISSUE TITLE
CSS -- add .dw th { text-align: center }

### ISSUE THREAD

**Issue by johnnyshields** [acidb/mobiscroll#174]
Bootstrap adds `th { text-align: left }`

It would be nice if the mobiscroll CSS could add 

``` css
.dw th {
  text-align: center;
}
```
