### ISSUE TITLE
Inconsistency in border radius rendering for Android ICS (Light) theme in modal mode for date/datetime pickers

### ISSUE THREAD

**Issue by ikarami** [acidb/mobiscroll#195]
I experienced this issue on a windows 7 based desktop with Chrome (31.0.1650.63 m) as well as in a default "Browser" on Samsung Galaxy S4 (4.2.2) and LG Nexus 4 (4.3). I was working with date/date-time pickers opened in a modal mode and themed with Android ICS Light. However, most probably it exists on a regular ICS and other pickers as well.

In Chrome the pressed state doesn't have rounded corners:
![mobiscroll_missing_border_radius](https://f.cloud.github.com/assets/1903145/1940908/b20b809a-7f81-11e3-8279-9a0f0fb3c216.png)

In Nexus 4 behavior is the same as above:
![mobiscroll_missing_border_radius_nexus](https://f.cloud.github.com/assets/1903145/1940937/26484b64-7f82-11e3-8933-8d52a924ae4b.png)

While on S4 corners are not rounded at all:
![device-2014-01-17-145950](https://f.cloud.github.com/assets/1903145/1940939/3f1ba9b0-7f82-11e3-9d94-54b397b8c923.png)

In order to fix this I have overridden the following mobiscroll styles (using LESS syntax):

``` css
.android-ics .dwbc span {
    &:first-of-type a {
        border-bottom-left-radius: 3px;
    }
    &:last-of-type a {
        border-bottom-right-radius: 3px;
    }
}
```

Although it's not a critical issue, it would be nice to have it fixed :)
