### ISSUE TITLE
Sliding months in Calendar with vertical direction can scroll the Document (Android)

### ISSUE THREAD

**Issue by Rendez** [acidb/mobiscroll#351]
I could not take a screenshot of the bug itself because the component autocorrects the position within 1 or 2 secs:

![bs_realdroid_mobile_samsung galaxy note 3-4 3-1080x1920](https://cloud.githubusercontent.com/assets/61776/9795202/8b56543c-57ef-11e5-8369-2710d48cbd24.jpg)
That's an Android 4.3 on a Galaxy Note 3, but we're able to reproduce this on 4.2.2 and potentially 4.4 and 5 (haven't tested the latter). This bug applies to Chrome and Native Android.

So the **bug** occurs when you slide months vertically very very fast, before you allow the animation to complete, or before the next month is "activated". Most likely it's because the Calendar does not capture the touchstart/touchmove/touchend sequence unless the calendar is finished animating and is active, and I'm sure there's a event.preventDefault(), but this doesn't prevent Android from scrolling down the page, losing the Calendar positioning. It's somehow resolved once the easing has finished, the `onscroll` event is triggered and the Component positions itself, but IMO provides a poor UX.

I am not sure there's an easy way to circumvent this problem solely with JS....

In the past, on similar components of our site, I've successfully blocked the scrolling of the Document with the help of CSS, to avoid this from happening:

```css
body { /* posible workaround */
   -webkit-overflow-scrolling: touch;
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: auto; /* iOS position:fixed; elements fix (not 100%) */
    min-height: 100%;
    overflow-x: hidden;
}
.dw {
   position: fixed;
    z-index: 9999;
    top: 0;
    left: 0;
    overflow-x: hidden;
    overflow-y: auto;
    width: 100%;
    height: 100%;
}
```

Thoughts?
